#application: nwkidsshow
application: cakidsshow
version: 9
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /favicon.ico
#  static_files: nwkidsshow/static/images/favicon-nwks.ico
  static_files: nwkidsshow/static/images/favicon-caks.ico
#  upload: nwkidsshow/static/images/favicon-nwks.ico
  upload: nwkidsshow/static/images/favicon-caks.ico
  expiration: '7d'

- url: /robots.txt
  static_files: nwkidsshow/robots.txt
  upload: nwkidsshow/robots.txt

- url: /static/css
  static_dir: nwkidsshow/static/css
  expiration: '1d'

- url: /static/images
  static_dir: nwkidsshow/static/images
  expiration: '1d'

- url: /static/admin
  static_dir: nwkidsshow/static/admin
  expiration: '1d'

- url: /.*
#  script: main.py
  script: main.app

libraries:
- name: django
  version: "1.5"

builtins:
- django_wsgi: on

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak
- ^(.*/)?.*\.mwb
- ^(.*/)?.*\.pdf
- ^(.*/)?.*\.db
- ^(.*/)?.*\.doc
- ^(.*/)?.*\.docx
- ^(.*/)?.*\.xls
- ^(.*/)?.*\.xlsx
